version: "2"
networks:
  vpc:
    driver: bridge

services:
  mysql:
    networks:
      vpc:
        aliases:
          - "localhost"
    container_name: "mysql"
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=kanban
      - MYSQL_DATABASE=kanban

  rest:
    networks:
      vpc:
        aliases:
         - "localhost"
    container_name: "rest-handler"
    build:
      context: ./target/docker
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - "mysql"
    links:
      - "mysql:localhost"
