version: "2.1"

services:
  mysql-kanban:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=kanban
      - MYSQL_DATABASE=kanban
      - MYSQL_USER=kanban
      - MYSQL_PASSWORD=kanban
  exbackend:
    image: exbackend
    depends_on:
      - mysql-kanban
    ports:
      - 8080:8080
    links:
      - mysql-kanban
    environment:
      - DATABASE_HOST=mysql-kanban
      - DATABASE_USER=kanban
      - DATABASE_PASSWORD=kanban
      - DATABASE_NAME=kanban
      - DATABASE_PORT=3306
