version: "2"
services:
  mysql:
    container_name: "mysql"
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=kanban
      - MYSQL_DATABASE=kanban

  rest:
    container_name: "rest-handler"
    build: ./target/docker
    ports:
      - 8080:8080
    depends_on:
      - "mysql"
    links:
      - "mysql"
